apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment #The name of the Kubernetes Deployment to be created in the Kubernetes cluster
  labels:
    app: api-services
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the api services application container
  selector:
    matchLabels:
      app: api-services
  template:
    metadata:
      labels:
        app: api-services
    spec:
      containers:
        - name: api-services #The name of the react.js application container
          image: anjannandy/startup-api-services #The Docker image for building the api-services application container
          ports:
            - containerPort: 8080 #The port for the React.js application   container


---

apiVersion: v1
kind: Service
metadata:
  name: service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: api-services
  type: LoadBalancer #Type of the Kubernetes Service
  ports:
    - protocol: TCP
      port: 8080 #Service port
      targetPort: 8080 #The port for the api services application container
