pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  environment {
    DOCKERHUB_CREDENTIALS = credentials('docker-hub')
  }
  stages {
    stage('Build') {
      steps {
        sh 'docker build -f api-services/api-services.dockerfile -t anjannandy/startup-api-services .'
      }
    }
    stage('Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Push') {
      steps {
        sh 'docker push anjannandy/startup-api-services'
      }
    }

    stage('Deploying api-services container to Kubernetes') {
        steps {
          script {
            kubernetesApply(
            configs: 'api-services/app.yaml',
             kubeconfigId: 'kubernetes-config'
             )
          }
        }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }


}
