spring:
  application:
    name: springboot-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.89:28080/auth/realms/startup
          jwk-set-uri: http://192.168.1.89:28080/auth/realms/startup/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: api-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG